language: php

php:
  - 7.1

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - cp .env.example .env
install:
  - composer install
  - php artisan key:generate
script:
  # Run tests
  - php artisan config:clear --no-interaction
  - ./vendor/bin/phpunit